### PR TITLE
add new volunteers

### PR DESCRIPTION
**Pull request by creisle**

### CODE REVIEW

**Review by miseminger — CHANGES_REQUESTED** [review]
Add Lenneth Li (?) to past volunteers list
Also Yerin?

**Comment by jwcodee** [comment]
I believe Yerin is still volunteering. It's just I think her role was YouTube upload so she's not currently that active.

**Comment by jwcodee** [comment]
Can you also update me too?  I'm a PhD student now. Thanks.

**Comment by creisle** [comment]
> I believe Yerin is still volunteering. It's just I think her role is YouTube recording upload so she's not currently that active.

@sunsetyerin what should I put for your affiliation etc?

**Comment by creisle** [comment]
> Add Lenneth Li (?) to past volunteers list Also Yerin?

anyone know for sure if lenneth's last name was li?

**Comment by creisle** [comment]
> Add Lenneth Li (?) to past volunteers list Also Yerin?

anyone know for sure if lenneth's last name was li?

**Comment by jwcodee** [comment]
> > Add Lenneth Li (?) to past volunteers list Also Yerin?
> 
> anyone know for sure if lenneth's last name was li?

According to the 2023-2024 critical path, his last name is Li

**Review by miseminger — APPROVED** [review]

**Pull request merged**
